name: Trigger SxT access token refresh

on:
  schedule:
    # Token expires every 30 minutes, so after 20 minutes, refresh it
    - cron: '0,20,40 * * * *'
jobs:
  build:
    name: SxT access token refresh
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: "curl -X POST --header 'Authorization: Bearer $BEARER_TOKEN' -d {} https://card.club/api/sxt/refresh"
        env:       
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}

